### ISSUE TITLE
Recheck hash

### ISSUE THREAD

**Issue by hasanAjsf** [GeekLaunch/blockchain-rust#1]
Hi, thanks for your videos and explanation, I'm studying it to understand better the blockchain, I've a question about this code block:

```rust
    pub fn mine (&mut self) {
        for nonce_attempt in 0..(u64::max_value()) {
            self.nonce = nonce_attempt;
            let hash = self.hash();
            if check_difficulty(&hash, self.difficulty) {
                self.hash = hash;
                return;
            }
        }
    }
```

Here, the hash is created based on the block data and required difficulty, and conceptual wise (if my understood correctly), I should be able to catch any data tampering within the block by recalculating the hash then comparing it with the `prev_hash_code` in the following block, how can I do this with the code above!!

**Comment by encody** [comment]
We go through blockchain verification in [this video](https://www.youtube.com/watch?v=buYvuIPdwHU). Also, I'm thinking it's probably best to keep GitHub issues for problems with the project instead of questions with the videos, so feel free to comment on the videos with whatever questions you have.
