### ISSUE TITLE
Code explanation 

### ISSUE THREAD

**Issue by hasanAjsf** [GeekLaunch/blockchain-rust#2]
I did not understand this code block, can you explain it pls:

```rust
pub fn u32_bytes (u: &u32) -> [u8; 4] {
    [
        (u >> 8 * 0x0) as u8,
        (u >> 8 * 0x1) as u8,
        (u >> 8 * 0x2) as u8,
        (u >> 8 * 0x3) as u8,
    ]
}
```

**Comment by encody** [comment]
Bytes are stored in little-endian order on most computers. That means if I have a 32-bit unsigned integer (`u32`) `0x12345678`, the bytes are ordered like so in memory: `0x78, 0x56, 0x34, 0x12`. This code uses bitshifting to create an array of these bytes in that order.
